apiVersion: batch/v1
kind: Job
metadata:
  name: data-generator
  labels:
    app: stateful-app
    job: data-generator
spec:
  template:
    metadata:
      labels:
        app: stateful-app
        job: data-generator
    spec:
      containers:
      - name: data-generator
        image: curlimages/curl:7.87.0
        command:
        - sh
        - -c
        - |
          # Wait for the API service to be ready
          echo "Waiting for API service to be ready..."
          until curl -s --head --fail ${APP_SERVICE_URL}/health; do 
            echo "Service not ready yet. Waiting 2 seconds..."
            sleep 2
          done
          
          # Generate the requested number of data records
          echo "Generating ${DATA_COUNT} records..."
          curl -s -X POST -H "Content-Type: application/json" \
            -d "{\"count\": ${DATA_COUNT}}" \
            "${APP_SERVICE_URL}/api/generate"
          
          # Report success
          echo "Data generation completed successfully!"
        env:
        - name: APP_SERVICE_URL
          value: "http://stateful-app-service"
        - name: DATA_COUNT
          value: "20"  # Change this to control how many records to create
      restartPolicy: OnFailure
  backoffLimit: 3  # Number of retries before job is marked as failed
  completions: 1   # Job completes after 1 successful pod
  parallelism: 1   # Run one pod at a time
